demographics_datadir: "../Demographics.jl/test/data/output"  # Directory containing saved population data. people = load(demographics_datadir)
output_directory: "data/output"  # Full path is /path/to/Covid.jl/data/output
firstday: 2020-01-18  # Simulation starts at 12am (initial state recorded at 11:59pm).
lastday:  2020-12-31  # Simulation finishes at 11:59pm (final state recorded at 11:59pm).
nruns: 10
params: "data/input/params.tsv"  # Full path is /path/to/Covid.jl/data/input/params.tsv
cumsum_population: "../Demographics.jl/test/data/input/population_by_SA2.tsv"

forcing:
    # 2020-02-01: {213011328: {E : 20 }, 
    #              213021343: {E : 20 , R : 500},
    #              313011328: {E : 20 }}
    2020-01-18: {Any : {E: 10}}
    2020-01-25: {Any : {E: 10}}
    2020-02-01: {Any : {E: 10}}
    2020-02-08: {Any : {E: 10}}
    2020-02-15: {Any : {E: 10}}
    2020-04-17: {Any : {E: 80}}    # Cedar Meats outbreak
    2020-04-24: {Any : {E: 80}}    # Fawkner McDonalds outbreak
    2020-06-01: {Any : {E: 100}}   # Security guard breaches, family gatherings, localised school outbreaks
    2020-06-06: {Any : {E: 500}}   # BLM protest Melbourne
    2020-06-08: {Any : {E: 100}}   # Security guard breaches, family gatherings, localised school outbreaks
    2020-06-15: {Any : {E: 100}}   # Security guard breaches, family gatherings, localised school outbreaks

# The physical distancing policy.
# The numbers are Pr(Contact a person in the contact list during any given day)
distancing_policy:
    2020-01-18: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}  # Normal.
    2020-03-23: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # Stage 1: Bars/restaurants/gyms/cinemas
    2020-03-24: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # School closures
    2020-03-25: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 2: Recreation, entertainment, retail, weddings/funerals.
    2020-03-30: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 3: Gatherings of <=2
    2020-04-27: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.04, social: 0.04}      # Social/community impatience
    2020-05-25: {household: 0.5, school: 0.1, workplace: 0.001, community: 0.04, social: 0.04}  # Schools partially reopen
    2020-05-30: {household: 0.5, school: 0.1, workplace: 0.001, community: 0.04, social: 0.06}  # Small gatherings at home
    2020-06-09: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.04, social: 0.06}  # Schools fully reopen (Tue after Queen's Birthday)
    2020-06-15: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}      # Scenario: Normal
    2020-07-08: {household: 0.5, school: 0.002, workplace: 0.001, community: 0.0001, social: 0.0001}  # Stage 3: Gatherings of <=2
    #2020-08-20: {household: 0.5, school: 0.2, workplace: 0.2, community: 0.1, social: 0.1}  # Normal.
    2020-08-20: {household: 0.5, school: 0.2, workplace: 0.001, community: 0.01, social: 0.01}  # Stage 1: Bars/restaurants/gyms/cinemas

# Pr(Test | Person is not a contact of a known case, status)
# Typically only people who are symptomatic and satisfy other criteria are tested
testing_policy:
    2020-01-18: {IS: 0.2, W: 0.5}  # Pre-pandemic testing
    2020-03-07: {IS: 0.5, W: 1.0}  # Pandemic testing
    2020-04-27: {IS: 0.8, W: 1.0}  # Testing blitz in Victoria
    2020-05-25: {IS: 0.5, W: 1.0}  # Resume pandemic testing
    2020-07-01: {IS: 0.8, W: 1.0}  # Blitz testing

# Pr(Test | Person is a contact of a known case, status)
# Asymptomatic contacts are S, E, IA or R.
# Symptomatic contacts are IS or H because W, ICU and V patients have already been tested upon admission to hospital.
tracing_policy:
    2020-01-18: {household: {symptomatic: 0.5, asymptomatic: 0.0}, school: {symptomatic: 0.0, asymptomatic: 0.0}, workplace: {symptomatic: 0.0, asymptomatic: 0.0}, community: {symptomatic: 0.0, asymptomatic: 0.0}, social: {symptomatic: 0.0, asymptomatic: 0.0}}
    2020-03-25: {household: {symptomatic: 1.0, asymptomatic: 0.9}, school: {symptomatic: 0.8, asymptomatic: 0.0}, workplace: {symptomatic: 0.5, asymptomatic: 0.1}, community: {symptomatic: 0.0, asymptomatic: 0.0}, social: {symptomatic: 0.1, asymptomatic: 0.0}}
    2020-05-04: {household: {symptomatic: 1.0, asymptomatic: 0.9}, school: {symptomatic: 0.8, asymptomatic: 0.0}, workplace: {symptomatic: 0.5, asymptomatic: 0.1}, community: {symptomatic: 0.02, asymptomatic: 0.0}, social: {symptomatic: 0.1, asymptomatic: 0.0}}
#    2020-06-15: {household: {symptomatic: 1.0, asymptomatic: 1.0}, school: {symptomatic: 1.0, asymptomatic: 1.0}, workplace: {symptomatic: 1.0, asymptomatic: 1.0}, community: {symptomatic: 1.0, asymptomatic: 1.0}, social: {symptomatic: 1.0, asymptomatic: 1.0}}

# People who are awaiting test results are quarantined until the result is available, which is currently 2 days after the test date.
# People who test positive are quarantined for X days after onset of symptoms if they are symptomatic (status=IS,H), or X days after the test date if asymptomatic.
# People known to be in recent contact with a known case are quarantined for X days.
quarantine_policy:
    2020-01-18: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7}, case_contacts: {household: {days: 14, compliance: 0.1}}}
    2020-03-15: {awaiting_test_result: {days: 2, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7}, case_contacts: {household: {days: 14, compliance: 0.1}, workplace: {days: 14, compliance: 0.1}}}
    2020-06-15: {awaiting_test_result: {days: 3, compliance: 0.7}, tested_positive: {days: 10, compliance: 0.7},
                 case_contacts: {household: {days: 14, compliance: 0.7}, workplace: {days: 14, compliance: 0.7}, school: {days: 14, compliance: 0.7}, community: {days: 14, compliance: 0.7}, social: {days: 14, compliance: 0.7}}}